---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: incrisz
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: incrisz
spec:
  selector:
    app: vote
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30300
  type: NodePort
  externalIPs:
  - 18.208.200.165
  - 18.208.200.165
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: incrisz
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: incrisz
spec:
  selector:
    app: result
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30400
  type: NodePort
